### ISSUE TITLE
How about using Zoom URL scheme to start the meeting directly?

### ISSUE THREAD

**Issue by x-creates** [ChromeAdmin/meetings-page-auto-closer-for-zoom#12]
Repacing `https` to `zoommtg` in a zoom meeting link could start the meeting with the Zoom client directly without opening the browser tab. Would that be nice to not open a new tab in the first place?

some ideas, `#1` hijack all link clicking, modify the zoom meeting URL on the fly or bypass those non Zoom links `#2` replace all zoom link `https` to `zoommtg` after page load (might be complicated for page with dynamic refresh components)

Only tested in macOS not sure if it would work for Windows or Linux

**REFERENCE**
- https://devforum.zoom.us/t/how-to-start-a-meeting-with-zoom-client-url-scheme/13577
- https://marketplace.zoom.us/docs/sdk/native-sdks/additional-tips/launch-zoom-client-from-your-app/
- https://github.com/YeonHo0718/zoom-url-scheme-example

**Comment by ChromeAdmin** [comment]
Thanks for the idea to prevent the tab from ever needing to be opened.

The idea is great but the implementation is non ideal. Like you correctly stated in `#1` this would require permission to all websites where the link URL would be re-written (and this solution would only work for href links not onClick). 

A more comprehensive solution would require using the powerful permission to intercept/redirect network requests. 

Due to the required invasive permissions needed, this extension will not be implementing those solutions.

Regarding your `#2`, the Zoom website is already attempting to launch the Zoom client. We don't think the user experience will be any different than the current ie. Tab is opened -> Zoom client launched -> Zoom tab is closed.

thoughts?

**Comment by xinyang-creates** [comment]
> #1 this would require permission to all websites where the link URL would be re-written (and this solution would only work for href links not onClick).

true, I did not think about the programmatic redirection. However, since most of the Zoom use cases start from Google calendar I think at least we can get the Google calendar (or other major calendar web app) part covered. They use `href` mostly.

> the Zoom website is already attempting to launch the Zoom client. We don't think the user experience will be any different than the current ie. Tab is opened -> Zoom client launched -> Zoom tab is closed.

`#2` is pretty similar to `#1` but pre-process the DOM.
